from typing import NotRequired, TypedDict

from .clob_types import BookParams, OrderBookSummary

class SimplifiedMarketsResponse(TypedDict):
    data: NotRequired[list[dict[str, object]]]
    next_cursor: NotRequired[str]

class ClobClient:
    def __init__(self, host: str) -> None: ...
    def get_simplified_markets(self, next_cursor: str = "MA==") -> SimplifiedMarketsResponse: ...
    def get_market(self, condition_id: str) -> dict[str, object]: ...
    def get_order_book(self, token_id: str) -> OrderBookSummary: ...
    def get_order_books(self, params: list[BookParams]) -> list[OrderBookSummary]: ...
    def get_midpoint(self, token_id: str) -> dict[str, object]: ...
    def get_price(self, token_id: str, side: str) -> dict[str, object]: ...
    def get_ok(self) -> object: ...
    def get_server_time(self) -> int | str | None: ...
